# Cloudflare Pages Configuration for PrivacyHub (Next.js)
name = "privacyhub"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# D1 Database binding for Pages Functions
[[d1_databases]]
binding = "an-db"
database_name = "privacyhub"
database_id = "b64e7663-7a31-4e38-a210-4c570dabd118"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Environment variables (set in Cloudflare Pages dashboard)
# OPENROUTER_API = <your-key>
# FIRECRAWL_API_KEY = <your-key>
