name = "privacyhub"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "an-db"
database_name = "privacyhub"
database_id = "b64e7663-7a31-4e38-a210-4c570dabd118"

# KV namespace for caching (optional, can use D1 for everything)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id" # Replace with actual KV namespace ID
preview_id = "your-preview-kv-namespace-id" # For preview deployments

# Environment variables
[vars]
NODE_ENV = "production"

# Secrets (set via wrangler secret put command)
# OPENROUTER_API
# FIRECRAWL_API_KEY

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"
