# Cloudflare Workers Configuration for PrivacyHub
name = "privacyhub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "an-db"
database_name = "privacyhub"
database_id = "b64e7663-7a31-4e38-a210-4c570dabd118"

# Environment variables (plaintext)
[vars]
NODE_ENV = "production"

# Secrets - set via Cloudflare Dashboard or wrangler secret put command
# OPENROUTER_API = <your-key>
# FIRECRAWL_API_KEY = <your-key>
