# Cloudflare Workers Configuration for PrivacyHub
name = "privacyhub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "an-db"
database_name = "privacyhub"
database_id = "b64e7663-7a31-4e38-a210-4c570dabd118"

# Environment variables (set in Cloudflare Workers dashboard)
# Secrets configured via dashboard:
# - FIRECRAWL_API_KEY
# - OPENROUTER_API
# - OPENROUTER_API_1
# - OPENROUTER_API_2
